### ISSUE TITLE
Fidelity between two mixed states

### ISSUE THREAD

**Issue by elib20** [XanaduAI/MrMustard#109]
### Before posting a feature request

- [X] I have searched exisisting GitHub issues to make sure the feature request does not already exist.

### Feature details

Compute the fidelity between two mixed states.

### Implementation

I tried using 
`trace( sqrtm( matmul( matmul( sqrtm(rho1), rho2), sqrtm(rho1) ) ) )**2`
but was hoping for something with a faster implementation.

### How important would you say this feature is?

2: Somewhat important. Needed this quarter.

**Comment by nquesada** [comment]
Is this for Gaussian states or general states?

**Comment by elib20** [comment]
General

**Comment by elib20** [comment]
If possible, can I elevate this to higher priority? @sduquemesa
