### ISSUE TITLE
Be able to export the State figure

### ISSUE THREAD

**Issue by sylviemonet** [XanaduAI/MrMustard#123]
### Before posting a feature request

- [X] I have searched exisisting GitHub issues to make sure the feature request does not already exist.

### Feature details

Add one option that I can get the data to plot the State (Wigner function) or it can be exported directly.

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by ziofil** [comment]
Hey Yuan, use this:

```python
from mrmustard.utils.graphics import mikkel_plot
```
and then `mikkel_plot(rho)` where `rho` is a 1-mode density matrix. You can set bounds with additional arguments.

**Comment by sduquemesa** [comment]
As per PR #179 `mikkel_plot` returns the figure and axis for further user processing.
