### ISSUE TITLE
Flag to turn on/off the progress bar in an optimization

### ISSUE THREAD

**Issue by elib20** [XanaduAI/MrMustard#128]
### Before posting a feature request

- [X] I have searched exisisting GitHub issues to make sure the feature request does not already exist.

### Feature details

The ability to turn on/off the progress bar while running an optimization.

### Implementation

I think the minimize function of the Optimizer class in utils/training.py can be modified as follows:

`    def minimize(
        self, cost_fn: Callable, by_optimizing: Sequence[Trainable], max_steps: int = 1000, progress_bar: bool = True
    ):
        r"""Minimizes the given cost function by optimizing circuits and/or detectors.

        Args:
            cost_fn (Callable): a function that will be executed in a differentiable context in
                order to compute gradients as needed
            by_optimizing (list of circuits and/or detectors and/or gates): a list of elements that
                contain the parameters to optimize
            max_steps (int): the minimization keeps going until the loss is stable or max_steps are
                reached (if ``max_steps=0`` it will only stop when the loss is stable)
        """
        try:
            params = {
                "symplectic": math.unique_tensors(
                    [p for item in by_optimizing for p in item.trainable_parameters["symplectic"]]
                ),
                "orthogonal": math.unique_tensors(
                    [p for item in by_optimizing for p in item.trainable_parameters["orthogonal"]]
                ),
                "euclidean": math.unique_tensors(
                    [p for item in by_optimizing for p in item.trainable_parameters["euclidean"]]
                ),
            }
            if progress_bar:
                bar = graphics.Progressbar(max_steps)
                with bar:
                    while not self.should_stop(max_steps):
                        cost, grads = math.value_and_gradients(cost_fn, params)
                        update_symplectic(params["symplectic"], grads["symplectic"], self.symplectic_lr)
                        update_orthogonal(params["orthogonal"], grads["orthogonal"], self.orthogonal_lr)
                        update_euclidean(params["euclidean"], grads["euclidean"], self.euclidean_lr)
                        self.opt_history.append(cost)
                        bar.step(math.asnumpy(cost))
            else:
                while not self.should_stop(max_steps):
                    cost, grads = math.value_and_gradients(cost_fn, params)
                    update_symplectic(params["symplectic"], grads["symplectic"], self.symplectic_lr)
                    update_orthogonal(params["orthogonal"], grads["orthogonal"], self.orthogonal_lr)
                    update_euclidean(params["euclidean"], grads["euclidean"], self.euclidean_lr)
                    self.opt_history.append(cost)
        except KeyboardInterrupt:  # graceful exit
            self.log.info("Optimizer execution halted due to keyboard interruption.")
            raise self.OptimizerInterruptedError() from None`

### How important would you say this feature is?

3: Very important! Blocking work.

**Comment by ziofil** [comment]
I'll make a quick PR

**Comment by ziofil** [comment]
Fixed! Now from the settings (`from mrmustard import settings`) you can toggle `settings.PROGRESSBAR = False` to turn it off.
