### ISSUE TITLE
Compute oscillator eigenstate for any angle

### ISSUE THREAD

**Issue by elib20** [XanaduAI/MrMustard#234]
### Before posting a feature request

- [x] I have searched exisisting GitHub issues to make sure the feature request does not already exist.

### Feature details

In physics.fock, there is a function to compute the Fock representation of oscillator eigenstates for the q-quadrature, i.e. <n|q>. It is simple to compute <n|R(phi)|q>=exp(i*n)<n|q> as well, but I am not good enough at tensorflow to figure out how to implement this myself.

### Implementation

Provide an extra phi argument to the function, and wherever the loop over n occurs, just add the extra complex phase to each term.

### How important would you say this feature is?

2: Somewhat important. Needed this quarter.

**Comment by ziofil** [comment]
if you are in a hurry this should work:

```python
cutoff = 10
q = math.arange(-1,1,0.1)
rot = math.diag_part(Rgate(0.5).U([cutoff]))[:,None]
q_to_n = math.cast(oscillator_eigenstate(q, cutoff), 'complex128')
rot * q_to_n
```

(double check the signs)

**Comment by ziofil** [comment]
This is available in lab_dev now
