### ISSUE TITLE
Autocutoffs not being respected

### ISSUE THREAD

**Issue by elib20** [XanaduAI/MrMustard#250]
### Before posting a bug report

- [X] I have searched exisisting GitHub issues to make sure the issue does not already exist.

### Expected behavior

I expect the cutoffs to be [10,10] in the first print statement, but they come out as [3,2].

This is obviously a problem when the BSgate is applied, since it keeps those same cutoffs.

```
from mrmustard import settings
from mrmustard.lab import *

settings.AUTOCUTOFF_MIN_CUTOFF = 10

print((Fock(2)&Fock(1)).cutoffs)

print(((Fock(2)&Fock(1)) >> BSgate(np.pi/4)).cutoffs)
```

### Actual behavior

See above.

### Reproduces how often

Every time.

### System information

```shell
Mr Mustard: a differentiable bridge between phase space and Fock space.
Copyright 2021 Xanadu Quantum Technologies Inc.

Python version:            3.10.11
Platform info:             Windows-10-10.0.19045-SP0
Installation path:         N/A
Mr Mustard version:        0.5.0-dev
Numpy version:             1.23.5
Numba version:             0.56.4
Scipy version:             1.10.1
The Walrus version:        0.20.0
TensorFlow version:        2.10.0
```

**Comment by ziofil** [comment]
See https://github.com/XanaduAI/MrMustard/issues/118#issuecomment-2043474066

**Comment by ziofil** [comment]
closing stale issues
