### ISSUE TITLE
All predefined states doesn't take the modes as the parameters

### ISSUE THREAD

**Issue by sylviemonet** [XanaduAI/MrMustard#270]
### Before posting a bug report

- [X] I have searched exisisting GitHub issues to make sure the issue does not already exist.

### Expected behavior

When genre predefined states, the modes information needs to be added into the init function of State.

### Actual behavior

No modes information is taken

### Reproduces how often

Each time when construct the circuit related to the label of modes.

### System information

```shell
Not relevant
```

**Comment by ziofil** [comment]
old MM issue, closing
