### ISSUE TITLE
Incorrect handling of mixed Gaussian states

### ISSUE THREAD

**Issue by jan-provaznik** [XanaduAI/MrMustard#292]
### Before posting a bug report

- [X] I have searched exisisting GitHub issues to make sure the issue does not already exist.

### Expected behavior

Given a Gaussian state one expects that `state.is_pure == state.is_hilbert_vector`.  However, the implementation of

- [is_hilbert_vector](https://github.com/XanaduAI/MrMustard/blob/develop/mrmustard/lab/abstract/state.py#L97) uses `np.allclose` with default value `atol` value, whereas
- [is_pure](https://github.com/XanaduAI/MrMustard/blob/develop/mrmustard/lab/abstract/state.py#L156) uses `np.isclose` with non-default value `atol = 1e-6`,

consequently allowing behavior where the state is considered both a vector in specific contexts and a density matrix at the same time. 

### Actual behavior

One incorrectly observes `state.is_pure != state.is_hilbert_vector`.

### Reproduces how often

Whenever `np.isclose(purity, 1.0, atol = 1e-6) != np.isclose(purity, 1.0)`. 
For example if `purity == 0.9999899`.

### System information

```shell
...
```

### Source code

```shell
fail_state = (
    mrmustard.lab.TMSV(r = 0.0115, modes = [ 0, 1 ])
    >> mrmustard.lab.Attenuator(transmissivity = 0.96)[1]
)
assert(fail_state.is_pure == fail_state.is_hilbert_vector)
```

**Comment by ziofil** [comment]
Hi Jan, thanks for finding this. We should use a consistent atol for the same quantities. This seems like an easy fix, would you like to open a PR for it?

**Comment by jan-provaznik** [comment]
I can do that tomorrow morning, no problem. On this note, could there be some use-cases where having the tolerance set through `Settings` would benefit the users?
