### ISSUE TITLE
Set cutoff based on contraction

### ISSUE THREAD

**Issue by elib20** [XanaduAI/MrMustard#396]
### Before posting a bug report

- [X] I have searched exisisting GitHub issues to make sure the issue does not already exist.

### Expected behavior

For objects in lab_dev, when contracting a Bargmann object with a Fock object, the Bargmann object should set its cutoff based on the Fock object.

### Actual behavior

The Bargmann object takes on the autocutoff.

### Reproduces how often

Every time.

### System information

```shell
N/A
```

**Comment by ziofil** [comment]
closing as it's a designed feature.
