### ISSUE TITLE
Make Mrmustard independent of SF

### ISSUE THREAD

**Issue by nquesada** [XanaduAI/MrMustard#61]
Currently MrMustard depends on Strawberry Fields. The dependency is only for using the Wigner function plotting capabilities of SF, which are in turn just borrowed from qutip. It would be nice to remove this very onerous requirement and make MrM independent of SF. Ideally one can simply take this method

https://github.com/XanaduAI/strawberryfields/blob/2c27f1c1ebe4bc53866dbe0420c9a6bafda5aeb4/strawberryfields/backends/states.py#L725

and turn it into a standalone function in the `utils/graphics.py` module. 

This would simplify the installation of MrM and since both MrM and SF might require different versions of TF avoid potentially dependency entanglements.

**Comment by ziofil** [comment]
done
