### ISSUE TITLE
Code without tests should not be merged

### ISSUE THREAD

**Issue by nquesada** [XanaduAI/MrMustard#79]
A policy should be instituted so that new code cannot be merged if it does not come with tests.

**Comment by thisac** [comment]
> 100% agree. @thisac Shall we add it to a contrib file?

A [development guide](https://github.com/XanaduAI/MrMustard/blob/doc/doc/development/development_guide.rst) is being added by @sduquemesa, containing a section on adding tests. We could, and probably should, add CodeCov as well to check for coverage.

**Comment by josh146** [comment]
CodeCov can't be added while the repo is private, _but_ it might be good to add `--cov=mrmustard --cov-report=term-missing` to the `tests.yml` test command in the interim

**Comment by nquesada** [comment]
I believe this repo is now public.

**Comment by josh146** [comment]
Oh how embarrassing, thanks for pointing that out @nquesada 🤦‍♂️

**Comment by thisac** [comment]
Closing this since we now have CodeCov set up.
